"""members fields

Revision ID: 1aa7f26dfe14
Revises: c69ec9ecd6ee
Create Date: 2026-01-06 19:40:24.448216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa7f26dfe14'
down_revision = 'c69ec9ecd6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=9), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('year')
        batch_op.drop_column('display_order')
        batch_op.drop_column('division')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
